---
- name: Build Linux Kernel from Source
  hosts: all
  vars_files:
    - vars/kernel_vars.yml

  tasks:
    - name: Include kernel build tasks
      ansible.builtin.import_tasks: tasks/build_kernel.yml 